# Generated by Django 5.0.1 on 2024-01-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransparentCaliforniaUC', '0002_rename_benefits_ucemployee_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucemployee',
            name='Benefits_currency',
        ),
        migrations.RemoveField(
            model_name='ucemployee',
            name='Other_Pay_currency',
        ),
        migrations.RemoveField(
            model_name='ucemployee',
            name='Overtime_Pay_currency',
        ),
        migrations.RemoveField(
            model_name='ucemployee',
            name='Regular_Pay_currency',
        ),
        migrations.RemoveField(
            model_name='ucemployee',
            name='Total_Pay_And_Benefits_currency',
        ),
        migrations.RemoveField(
            model_name='ucemployee',
            name='Total_Pay_currency',
        ),
        migrations.AlterField(
            model_name='ucemployee',
            name='Benefits',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ucemployee',
            name='Other_Pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ucemployee',
            name='Overtime_Pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ucemployee',
            name='Regular_Pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ucemployee',
            name='Total_Pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ucemployee',
            name='Total_Pay_And_Benefits',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
