# Generated by Django 5.0.1 on 2024-01-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransparentCaliforniaUC', '0003_remove_ucemployee_benefits_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ucemployee',
            options={'ordering': ['ID']},
        ),
    ]
